// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const DeployTypes: typeof import('/@/views/Projects/constants.ts')['DeployTypes'];
}
export {};
